name: Deploy to Vercel

on:
  push:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.12"

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        version: "latest"
        
    - name: Install dependencies
      run: |
        uv sync
        
    - name: Run tests
      run: |
        uv run pytest tests/ -v --tb=short
      env:
        SECRET_KEY: test-secret-key
        DATABASE_URL: sqlite:///test.db
        STRIPE_SECRET_KEY: sk_test_dummy
        STRIPE_PUBLISHABLE_KEY: pk_test_dummy
        GOOGLE_CLOUD_PROJECT: test-project
        GEMINI_API_KEY: test-key
        ENVIRONMENT: test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'