name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, cs2pr

      - name: Lint PHP Files
        run: |
          ERROR_COUNT=0
          for file in $(find upload -type f -name "*.php" ! -path 'upload/system/storage/vendor/*'); do
            if ! php -l -n "$file" > /dev/null 2>&1; then
              echo "Syntax error in: $file"
              php -l -n "$file"
              ERROR_COUNT=$((ERROR_COUNT + 1))
            fi
          done
          if [ $ERROR_COUNT -gt 0 ]; then
            echo "Found $ERROR_COUNT PHP syntax errors."
            exit 1
          else
            echo "No syntax errors were detected."
          fi

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/composer/files
            ./.cache
            ./.php-cs-fixer.cache
          key: ${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ matrix.php }}-

      - name: Install Dependencies
        run: composer install

      - name: Check Code Style
        if: matrix.php == '8.3'
        run: |
          php tools/php-cs-fixer.phar fix --dry-run --diff --ansi || true
          php tools/php-cs-fixer.phar fix --dry-run --format=checkstyle | cs2pr

      - name: Run PHPStan
        run: php tools/phpstan.phar analyze --no-progress
        continue-on-error: true
